const COUNTRY_NAME_BY_CODE = {
  AD: "Andorra",
  AE: "United Arab Emirates",
  AF: "Afghanistan",
  AG: "Antigua and Barbuda",
  AI: "Anguilla",
  AL: "Albania",
  AM: "Armenia",
  AO: "Angola",
  AQ: "Antarctica",
  AR: "Argentina",
  AS: "American Samoa",
  AT: "Austria",
  AU: "Australia",
  AW: "Aruba",
  AX: "Aland Islands",
  AZ: "Azerbaijan",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint Barthelemy",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  BQ: "Caribbean Netherlands",
  BR: "Brazil",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvet Island",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Canada",
  CC: "Cocos (Keeling) Islands",
  CD: "Democratic Republic of the Congo",
  CF: "Central African Republic",
  CG: "Republic of the Congo",
  CH: "Switzerland",
  CI: "Cote d'Ivoire",
  CK: "Cook Islands",
  CL: "Chile",
  CM: "Cameroon",
  CN: "China",
  CO: "Colombia",
  CR: "Costa Rica",
  CU: "Cuba",
  CV: "Cape Verde",
  CW: "Curacao",
  CX: "Christmas Island",
  CY: "Cyprus",
  CZ: "Czechia",
  DE: "Germany",
  DJ: "Djibouti",
  DK: "Denmark",
  DM: "Dominica",
  DO: "Dominican Republic",
  DZ: "Algeria",
  EC: "Ecuador",
  EE: "Estonia",
  EG: "Egypt",
  EH: "Western Sahara",
  ER: "Eritrea",
  ES: "Spain",
  ET: "Ethiopia",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Micronesia",
  FO: "Faroe Islands",
  FR: "France",
  GA: "Gabon",
  GB: "United Kingdom",
  GD: "Grenada",
  GE: "Georgia",
  GF: "French Guiana",
  GG: "Guernsey",
  GH: "Ghana",
  GI: "Gibraltar",
  GL: "Greenland",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe",
  GQ: "Equatorial Guinea",
  GR: "Greece",
  GS: "South Georgia and the South Sandwich Islands",
  GT: "Guatemala",
  GU: "Guam",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hong Kong",
  HM: "Heard Island and McDonald Islands",
  HN: "Honduras",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  ID: "Indonesia",
  IE: "Ireland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "India",
  IO: "British Indian Ocean Territory",
  IQ: "Iraq",
  IR: "Iran",
  IS: "Iceland",
  IT: "Italy",
  JE: "Jersey",
  JM: "Jamaica",
  JO: "Jordan",
  JP: "Japan",
  KE: "Kenya",
  KG: "Kyrgyzstan",
  KH: "Cambodia",
  KI: "Kiribati",
  KM: "Comoros",
  KN: "Saint Kitts and Nevis",
  KP: "North Korea",
  KR: "South Korea",
  KW: "Kuwait",
  KY: "Cayman Islands",
  KZ: "Kazakhstan",
  LA: "Laos",
  LB: "Lebanon",
  LC: "Saint Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Lithuania",
  LU: "Luxembourg",
  LV: "Latvia",
  LY: "Libya",
  MA: "Morocco",
  MC: "Monaco",
  MD: "Moldova",
  ME: "Montenegro",
  MF: "Saint Martin",
  MG: "Madagascar",
  MH: "Marshall Islands",
  MK: "North Macedonia",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolia",
  MO: "Macau",
  MP: "Northern Mariana Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MS: "Montserrat",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Maldives",
  MW: "Malawi",
  MX: "Mexico",
  MY: "Malaysia",
  MZ: "Mozambique",
  NA: "Namibia",
  NC: "New Caledonia",
  NE: "Niger",
  NF: "Norfolk Island",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue",
  NZ: "New Zealand",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PH: "Philippines",
  PK: "Pakistan",
  PL: "Poland",
  PM: "Saint Pierre and Miquelon",
  PN: "Pitcairn",
  PR: "Puerto Rico",
  PS: "Palestine",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Qatar",
  RE: "Reunion",
  RO: "Romania",
  RS: "Serbia",
  RU: "Russia",
  RW: "Rwanda",
  SA: "Saudi Arabia",
  SB: "Solomon Islands",
  SC: "Seychelles",
  SD: "Sudan",
  SE: "Sweden",
  SG: "Singapore",
  SH: "Saint Helena, Ascension and Tristan da Cunha",
  SI: "Slovenia",
  SJ: "Svalbard and Jan Mayen",
  SK: "Slovakia",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "South Sudan",
  ST: "Sao Tome and Principe",
  SV: "El Salvador",
  SX: "Sint Maarten",
  SY: "Syria",
  SZ: "Eswatini",
  TC: "Turks and Caicos Islands",
  TD: "Chad",
  TF: "French Southern Territories",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tajikistan",
  TK: "Tokelau",
  TL: "Timor-Leste",
  TM: "Turkmenistan",
  TN: "Tunisia",
  TO: "Tonga",
  TR: "Turkey",
  TT: "Trinidad and Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tanzania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "United States Minor Outlying Islands",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VA: "Vatican City",
  VC: "Saint Vincent and the Grenadines",
  VE: "Venezuela",
  VG: "British Virgin Islands",
  VI: "U.S. Virgin Islands",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis and Futuna",
  WS: "Samoa",
  YE: "Yemen",
  YT: "Mayotte",
  ZA: "South Africa",
  ZM: "Zambia",
  ZW: "Zimbabwe"
} as const;

type CountryCode = keyof typeof COUNTRY_NAME_BY_CODE;

const COUNTRY_ALIAS_TO_CODE: Record<string, CountryCode> = {
  "america": "US",
  "bolivia, plurinational state of": "BO",
  "brunei darussalam": "BN",
  "britain": "GB",
  "british virgin islands": "VG",
  "burma": "MM",
  "cabo verde": "CV",
  "congo": "CG",
  "congo brazzaville": "CG",
  "congo kinshasa": "CD",
  "congo republic": "CG",
  "cote d ivoire": "CI",
  "cote d'ivoire": "CI",
  "curaçao": "CW",
  "democratic people's republic of korea": "KP",
  "democratic republic of congo": "CD",
  "democratic republic of the congo": "CD",
  "dprk": "KP",
  "dr congo": "CD",
  "drc": "CD",
  "england": "GB",
  "federated states of micronesia": "FM",
  "great britain": "GB",
  "holy see": "VA",
  "hong kong sar": "HK",
  "hong kong sar china": "HK",
  "iran, islamic republic of": "IR",
  "islamic republic of iran": "IR",
  "ivory coast": "CI",
  "lao people's democratic republic": "LA",
  "macao": "MO",
  "macao special administrative region of china": "MO",
  "macedonia": "MK",
  "micronesia, federated states of": "FM",
  "myanmar (burma)": "MM",
  "north korea": "KP",
  "northern ireland": "GB",
  "palestinian territories": "PS",
  "palestinian territory": "PS",
  "republic of congo": "CG",
  "republic of korea": "KR",
  "republic of moldova": "MD",
  "reunion": "RE",
  "russian federation": "RU",
  "scotland": "GB",
  "south korea": "KR",
  "state of palestine": "PS",
  "st barthelemy": "BL",
  "st. barthelemy": "BL",
  "st helena": "SH",
  "st kitts and nevis": "KN",
  "st lucia": "LC",
  "st martin": "MF",
  "st pierre and miquelon": "PM",
  "st vincent and the grenadines": "VC",
  "st. helena": "SH",
  "st. kitts and nevis": "KN",
  "st. lucia": "LC",
  "st. martin": "MF",
  "st. pierre and miquelon": "PM",
  "st. vincent and the grenadines": "VC",
  "swaziland": "SZ",
  "syrian arab republic": "SY",
  "taiwan, province of china": "TW",
  "the democratic republic of the congo": "CD",
  "timor leste": "TL",
  "turkiye": "TR",
  "u.k.": "GB",
  "u.s.": "US",
  "u.s.a.": "US",
  "u.s. virgin islands": "VI",
  "u.k": "GB",
  "u.s": "US",
  "u.s.a": "US",
  "uae": "AE",
  "uk": "GB",
  "united kingdom of great britain and northern ireland": "GB",
  "united republic of tanzania": "TZ",
  "united states of america": "US",
  "united states virgin islands": "VI",
  "us virgin islands": "VI",
  "usa": "US",
  "venezuela, bolivarian republic of": "VE",
  "viet nam": "VN",
  "vietnam": "VN",
  "vatican": "VA",
  "wales": "GB"
};

const FLAG_OFFSET = 127397;

function normalizeLookupValue(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
    .replace(/\s+/g, " ");
}

const COUNTRY_CODE_BY_LOOKUP = new Map<string, CountryCode>();

for (const [code, name] of Object.entries(COUNTRY_NAME_BY_CODE) as [CountryCode, string][]) {
  COUNTRY_CODE_BY_LOOKUP.set(normalizeLookupValue(code), code);
  COUNTRY_CODE_BY_LOOKUP.set(normalizeLookupValue(name), code);
}

for (const [alias, code] of Object.entries(COUNTRY_ALIAS_TO_CODE) as [string, CountryCode][]) {
  COUNTRY_CODE_BY_LOOKUP.set(normalizeLookupValue(alias), code);
}

function getFlagFromCountryCode(code: CountryCode) {
  return Array.from(code)
    .map((character) => String.fromCodePoint(FLAG_OFFSET + character.charCodeAt(0)))
    .join("");
}

export type ResolvedCountry = {
  code: CountryCode | null;
  name: string;
  flag: string | null;
};

export function resolveCountry(value: string | null | undefined): ResolvedCountry {
  const originalValue = typeof value === "string" ? value.trim() : "";

  if (!originalValue) {
    return {
      code: null,
      name: "",
      flag: null
    };
  }

  const directCode = originalValue.toUpperCase();
  const resolvedCode =
    COUNTRY_NAME_BY_CODE[directCode as CountryCode]
      ? (directCode as CountryCode)
      : COUNTRY_CODE_BY_LOOKUP.get(normalizeLookupValue(originalValue)) ?? null;

  if (!resolvedCode) {
    return {
      code: null,
      name: originalValue,
      flag: null
    };
  }

  return {
    code: resolvedCode,
    name: COUNTRY_NAME_BY_CODE[resolvedCode],
    flag: getFlagFromCountryCode(resolvedCode)
  };
}

export function normalizeCountryForStorage(value: string | null | undefined) {
  return resolveCountry(value).name;
}
