ALTER TABLE "Post" ADD COLUMN "mediaAspectRatio" TEXT;
ALTER TABLE "Post" ADD COLUMN "mediaWidth" INTEGER;
ALTER TABLE "Post" ADD COLUMN "mediaHeight" INTEGER;
ALTER TABLE "Post" ADD COLUMN "cropZoom" DOUBLE PRECISION;
ALTER TABLE "Post" ADD COLUMN "cropOffsetX" DOUBLE PRECISION;
ALTER TABLE "Post" ADD COLUMN "cropOffsetY" DOUBLE PRECISION;
