ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "mediaAspectRatio" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "mediaWidth" INTEGER;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "mediaHeight" INTEGER;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "cropZoom" DOUBLE PRECISION;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "cropOffsetX" DOUBLE PRECISION;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "cropOffsetY" DOUBLE PRECISION;
